[package]
name = "trantor"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = { version = "0.3", features = ["tls", "compression-gzip"] }
ulid = "1"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.6", features = [
  "runtime-tokio-native-tls",
  "postgres",
  "chrono",
  "json",
  "bigdecimal",
  "offline",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uaparser = "0.6"
base64 = "0.21"
num-traits = "0.2"
include_dir = { version = "0.7.3", features = ["metadata"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing = "0.1"
toml = "0.7.4"
color-eyre = "0.6.2"
maxminddb = "0.23.0"
async-trait = "0.1.68"
thiserror = "1.0.40"

domain = { path = "domain" }

[profile.dev.package.sqlx-macros]
opt-level = 3

[workspace]
members = ["domain", "pg-repositories", "services", "warp-controller"]
