CREATE TABLE sources (
  id SERIAL PRIMARY KEY,
  name VARCHAR(25) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS visitors (
  id SERIAL PRIMARY KEY,
  visitor_id CHAR(26) NOT NULL UNIQUE,
  referer VARCHAR(255) NOT NULL,
  user_agent VARCHAR(255) NOT NULL,
  user_agent_parsed JSON NOT NULL,
  source_id INTEGER NULL REFERENCES sources(id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE sessions (
  id SERIAL PRIMARY KEY,
  session_id CHAR(26) NOT NULL UNIQUE,
  visitor_id INTEGER NOT NULL REFERENCES visitors(id),
  start_timestamp TIMESTAMP NOT NULL,
  end_timestamp TIMESTAMP NULL,
  title VARCHAR(255) NOT NULL,
  pathname VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ended_at TIMESTAMP NULL
);
CREATE TABLE events (
  id SERIAL PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES sessions(id),
  type VARCHAR(255) NOT NULL,
  target VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);