[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
ulid = "1.0.0"
tracing = "0.1.37"
thiserror = "1.0.40"
async-trait = "0.1.68"
serde = { version = "1.0.164", features = ["derive"] }
